const en = {
  retry: 'Retry', no_results: 'No results found.', pagination: 'Pagination', previous: 'Previous', next: 'Next', page_of: 'Page {page} of {pages}', total_items: '{total} records', clear_search: 'Clear search', choose_role: 'Choose a role', choose_project: 'Choose a project', access_denied: 'Access denied', no_permission: 'Your account does not have access to this page.', connection_checking: 'Checking connection', connection_online: 'Connected', connection_offline: 'Connection unavailable', discard_changes: 'Discard your unsaved changes?', upload: 'Upload', upload_progress: 'Uploading: {percent}%', processing: 'Upload complete. Processing and saving…', new_pages_append: 'New pages are appended after the existing pages. Reorder them before saving.', edit_user: 'Edit reader', username: 'Username', email: 'Email', coins: 'Lightning balance', reader_readonly: 'Identity and cosmetics are read-only here. Use the balance action to adjust Lightning.', active_account: 'Account is active', reject: 'Reject', rejection_reason: 'Reason for rejection', rejection_help: 'Explain what needs to change so the creator can resubmit.', unknown: 'Unknown', unavailable: 'Unavailable', error: 'Unable to complete the action.', unsaved_changes: 'Unsaved changes', total_readers: 'Total readers'
}
const ru = {
  retry: 'Повторить', no_results: 'Ничего не найдено.', pagination: 'Навигация по страницам', previous: 'Назад', next: 'Далее', page_of: 'Страница {page} из {pages}', total_items: 'Записей: {total}', clear_search: 'Очистить поиск', choose_role: 'Выберите роль', choose_project: 'Выберите проект', access_denied: 'Доступ запрещён', no_permission: 'У вашей учётной записи нет доступа к этой странице.', connection_checking: 'Проверка подключения', connection_online: 'Подключено', connection_offline: 'Подключение недоступно', discard_changes: 'Отменить несохранённые изменения?', upload: 'Загрузка', upload_progress: 'Загрузка: {percent}%', processing: 'Загрузка завершена. Обработка и сохранение…', new_pages_append: 'Новые страницы добавляются после существующих. Измените их порядок перед сохранением.', edit_user: 'Редактировать читателя', username: 'Имя пользователя', email: 'Электронная почта', coins: 'Баланс молний', reader_readonly: 'Имя, почта и оформление доступны только для просмотра. Для изменения молний используйте действие с балансом.', active_account: 'Учётная запись активна', reject: 'Отклонить', rejection_reason: 'Причина отклонения', rejection_help: 'Объясните, что нужно изменить для повторной отправки.', unknown: 'Неизвестно', unavailable: 'Недоступно', error: 'Не удалось выполнить действие.', unsaved_changes: 'Несохранённые изменения', total_readers: 'Всего читателей'
}
const uz = {
  retry: 'Qayta urinish', no_results: 'Natijalar topilmadi.', pagination: 'Sahifalar', previous: 'Oldingi', next: 'Keyingi', page_of: '{pages} sahifadan {page}-sahifa', total_items: '{total} ta yozuv', clear_search: 'Qidiruvni tozalash', choose_role: 'Rolni tanlang', choose_project: 'Loyihani tanlang', access_denied: 'Kirish taqiqlangan', no_permission: 'Hisobingizda ushbu sahifaga kirish huquqi yo‘q.', connection_checking: 'Ulanish tekshirilmoqda', connection_online: 'Ulangan', connection_offline: 'Ulanish mavjud emas', discard_changes: 'Saqlanmagan o‘zgarishlarni bekor qilasizmi?', upload: 'Yuklash', upload_progress: 'Yuklanmoqda: {percent}%', processing: 'Yuklash tugadi. Qayta ishlash va saqlash…', new_pages_append: 'Yangi sahifalar mavjud sahifalardan keyin qo‘shiladi. Saqlashdan oldin ularning tartibini o‘zgartiring.', edit_user: 'O‘quvchini tahrirlash', username: 'Foydalanuvchi nomi', email: 'Elektron pochta', coins: 'Chaqmoq balansi', reader_readonly: 'Shaxsiy ma’lumotlar va bezaklarni bu yerda faqat ko‘rish mumkin. Chaqmoqni o‘zgartirish uchun balans amalidan foydalaning.', active_account: 'Hisob faol', reject: 'Rad etish', rejection_reason: 'Rad etish sababi', rejection_help: 'Creator qayta yuborishi uchun nimalarni o‘zgartirish kerakligini tushuntiring.', unknown: 'Noma’lum', unavailable: 'Mavjud emas', error: 'Amalni bajarib bo‘lmadi.', unsaved_changes: 'Saqlanmagan o‘zgarishlar', total_readers: 'Jami o‘quvchilar'
}
const transactions = {
  en: { chapter_read: 'Chapter read', daily_checkin: 'Daily check-in', register_bonus: 'Welcome bonus', shop_purchase: 'Shop purchase', admin_adjustment: 'Balance adjustment', admin_gift: 'Staff gift', wheel_spin: 'Wheel spin', wheel_reward: 'Wheel reward', clan_create: 'Clan creation', clan_upgrade: 'Clan upgrade' },
  ru: { chapter_read: 'Чтение главы', daily_checkin: 'Ежедневный вход', register_bonus: 'Бонус регистрации', shop_purchase: 'Покупка в магазине', admin_adjustment: 'Корректировка баланса', admin_gift: 'Подарок от администрации', wheel_spin: 'Вращение колеса', wheel_reward: 'Приз колеса', clan_create: 'Создание клана', clan_upgrade: 'Улучшение клана' },
  uz: { chapter_read: 'Bob o‘qish', daily_checkin: 'Kunlik kirish', register_bonus: 'Ro‘yxatdan o‘tish bonusi', shop_purchase: 'Do‘kondagi xarid', admin_adjustment: 'Balans tuzatishi', admin_gift: 'Admin sovg‘asi', wheel_spin: 'Charx aylantirish', wheel_reward: 'Charx yutug‘i', clan_create: 'Klan ochish', clan_upgrade: 'Klan darajasini oshirish' }
}
const cooldown = { en: 'Minutes between chapter reward claims (0 disables)', ru: 'Минут между получениями награды за главы (0 отключает)', uz: 'Bob mukofotlarini olish orasidagi daqiqalar (0 o‘chiradi)' }
const additional = {
  en: { reader: 'Reader', chapter_suffix: ' — chapter', all: 'All', disabled: 'disabled', saving: 'Saving…', untitled: 'Untitled', browser: 'Browser' },
  ru: { reader: 'Читатель', chapter_suffix: ' — глава', all: 'Все', disabled: 'отключён', saving: 'Сохранение…', untitled: 'Без названия', browser: 'Браузер' },
  uz: { reader: 'O‘quvchi', chapter_suffix: '-bob', all: 'Barchasi', disabled: 'nofaol qilindi', saving: 'Saqlanmoqda…', untitled: 'Sarlavhasiz', browser: 'Brauzer' }
}
const apiErrors = {
  en: { session: 'Your session expired. Sign in again.', access: 'Your account cannot perform this action.', not_found: 'This record is no longer available.', conflict: 'This action conflicts with the current data. Refresh and review your changes.', validation: 'Check the required fields, values and file requirements.', rate_limit: 'Too many requests. Wait a moment and retry.', offline: 'The server could not be reached. Check your connection and retry.', server: 'The server could not complete this action. Your draft is retained. Retry shortly.', daily_limit: 'The daily chapter reward limit has been reached.', wait_reward: 'Wait for the reward cooldown before claiming again.', insufficient_coins: 'The account has insufficient Lightning.', duplicate: 'This name, email or record is already in use.', duplicate_chapter: 'That chapter number already exists. Choose another number.', file_size: 'Images must be no larger than 20 MB each.', file_type: 'Use JPEG, PNG, GIF or WebP images.' },
  ru: { session: 'Сеанс истёк. Войдите снова.', access: 'Ваша учётная запись не может выполнить это действие.', not_found: 'Эта запись больше недоступна.', conflict: 'Действие противоречит текущим данным. Обновите страницу и проверьте изменения.', validation: 'Проверьте обязательные поля, значения и требования к файлам.', rate_limit: 'Слишком много запросов. Подождите и повторите.', offline: 'Сервер недоступен. Проверьте подключение и повторите.', server: 'Не удалось выполнить действие. Черновик сохранён. Повторите позже.', daily_limit: 'Достигнут суточный лимит наград за главы.', wait_reward: 'Подождите перед следующим получением награды.', insufficient_coins: 'На счёте недостаточно молний.', duplicate: 'Это имя, почта или запись уже используется.', duplicate_chapter: 'Глава с этим номером уже существует. Выберите другой номер.', file_size: 'Размер каждого изображения должен быть не более 20 МБ.', file_type: 'Используйте изображения JPEG, PNG, GIF или WebP.' },
  uz: { session: 'Seans tugadi. Qayta kiring.', access: 'Hisobingiz ushbu amalni bajara olmaydi.', not_found: 'Ushbu yozuv mavjud emas.', conflict: 'Amal joriy ma’lumotlarga zid. Sahifani yangilab o‘zgarishlarni tekshiring.', validation: 'Majburiy maydonlar, qiymatlar va fayl talablarini tekshiring.', rate_limit: 'So‘rovlar juda ko‘p. Biroz kutib qayta urining.', offline: 'Serverga ulanib bo‘lmadi. Ulanishni tekshirib qayta urining.', server: 'Server amalni bajara olmadi. Kiritgan ma’lumotlaringiz saqlangan. Birozdan keyin qayta urining.', daily_limit: 'Bob mukofotlarining kunlik chegarasiga yetildi.', wait_reward: 'Keyingi mukofotdan oldin biroz kuting.', insufficient_coins: 'Hisobda Chaqmoq yetarli emas.', duplicate: 'Ushbu nom, pochta yoki yozuv band.', duplicate_chapter: 'Ushbu raqamli bob allaqachon mavjud. Boshqa raqam tanlang.', file_size: 'Har bir rasm 20 MB dan oshmasligi kerak.', file_type: 'JPEG, PNG, GIF yoki WebP rasmlaridan foydalaning.' }
}
const states = {
  en: { open: 'Open', closed: 'Closed', no: 'No', free: 'Free', available_for_sale: 'is available for sale' },
  ru: { open: 'Открыт', closed: 'Закрыт', no: 'Нет', free: 'Бесплатно', available_for_sale: 'доступен в продаже' },
  uz: { open: 'Ochiq', closed: 'Yopiq', no: 'Yo‘q', free: 'Bepul', available_for_sale: 'sotuvga chiqarildi' }
}
apiErrors.en.shop_in_use = 'Readers own this item or a wheel uses it. Hide it from sale instead of deleting it.'
apiErrors.ru.shop_in_use = 'Предмет уже есть у читателей или используется колесом. Скрывайте его из продажи вместо удаления.'
apiErrors.uz.shop_in_use = 'Buyum o‘quvchilarda mavjud yoki charxda ishlatiladi. Uni o‘chirish o‘rniga sotuvdan yashiring.'
apiErrors.en.invalid_credentials = 'Incorrect email/username or password. Please try again.'
apiErrors.ru.invalid_credentials = 'Неверная почта, имя пользователя или пароль. Попробуйте снова.'
apiErrors.uz.invalid_credentials = 'Email, foydalanuvchi nomi yoki parol noto‘g‘ri. Qayta urining.'
states.en.activated = 'was activated'
states.en.blocked = 'was blocked'
states.ru.activated = 'активирован'
states.ru.blocked = 'заблокирован'
states.uz.activated = 'faollashtirildi'
states.uz.blocked = 'bloklandi'
export default Object.fromEntries(Object.entries({ en, ru, uz }).map(([locale, common]) => [locale, { common: { ...common, ...additional[locale], ...states[locale], cooldown: cooldown[locale] }, apiErrors: apiErrors[locale], nav: { menu: { en: 'Navigation menu', ru: 'Меню навигации', uz: 'Navigatsiya menyusi' }[locale] }, transactions: transactions[locale] }]))
