"""initial_schema

Revision ID: 9a8af726b732
Revises:
Create Date: 2026-09-29 15:51:10.742198
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a8af726b732'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan_level_configs',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('required_xp', sa.Integer(), nullable=False),
    sa.Column('upgrade_cost_coins', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('perks_description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('level')
    )
    with op.batch_alter_table('clan_level_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clan_level_configs_level'), ['level'], unique=False)

    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genres_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_genres_slug'), ['slug'], unique=True)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('price_coins', sa.Integer(), nullable=False),
    sa.Column('asset_url', sa.String(length=500), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shop_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shop_items_item_type'), ['item_type'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('lightning_coins', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('last_daily_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('wheels',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_coins', sa.Integer(), nullable=False),
    sa.Column('has_daily_free_spin', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wheels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wheels_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wheels_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_wheels_slug'), ['slug'], unique=True)

    op.create_table('clans',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tag', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('frame_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('is_recruiting', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clans_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_clans_tag'), ['tag'], unique=True)

    op.create_table('friendships',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('friend_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_friendship_user_friend')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendships_friend_id'), ['friend_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_user_id'), ['user_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('staff_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_users_username'), ['username'], unique=True)

    op.create_table('user_inventory',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_user_shop_item')
    )
    with op.batch_alter_table('user_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_inventory_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('wheel_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('wheel_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reward_type', sa.String(length=30), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=True),
    sa.Column('shop_item_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('text_color', sa.String(length=30), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_jackpot', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wheel_id'], ['wheels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wheel_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wheel_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wheel_items_wheel_id'), ['wheel_id'], unique=False)

    op.create_table('clan_members',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('clan_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('contribution_points', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clan_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clan_members_clan_id'), ['clan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_members_user_id'), ['user_id'], unique=True)

    op.create_table('clan_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('clan_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clan_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clan_messages_clan_id'), ['clan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clan_messages_user_id'), ['user_id'], unique=False)

    op.create_table('coin_transactions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_staff_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coin_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_coin_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('creator_requests',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_requests_user_id'), ['user_id'], unique=True)

    op.create_table('staff_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_sessions_staff_id'), ['staff_id'], unique=False)

    op.create_table('webtoons',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=True),
    sa.Column('uploader_staff_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_staff_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webtoons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webtoons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webtoons_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_webtoons_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_webtoons_type'), ['type'], unique=False)

    op.create_table('wheel_spins',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('wheel_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('wheel_item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_free_spin', sa.Boolean(), nullable=False),
    sa.Column('cost_paid', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=30), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=True),
    sa.Column('reward_label', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wheel_id'], ['wheels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wheel_item_id'], ['wheel_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wheel_spins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wheel_spins_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wheel_spins_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wheel_spins_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wheel_spins_wheel_id'), ['wheel_id'], unique=False)

    op.create_table('bookmarks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('webtoon_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webtoon_id'], ['webtoons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'webtoon_id', name='uq_user_webtoon_bookmark')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmarks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_webtoon_id'), ['webtoon_id'], unique=False)

    op.create_table('chapters',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('webtoon_id', sa.BigInteger(), nullable=False),
    sa.Column('chapter_number', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['webtoon_id'], ['webtoons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_chapter_number'), ['chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_webtoon_id'), ['webtoon_id'], unique=False)

    op.create_table('webtoon_genres',
    sa.Column('webtoon_id', sa.BigInteger(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webtoon_id'], ['webtoons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('webtoon_id', 'genre_id')
    )
    op.create_table('chapter_images',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_images_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_images_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_images_order_index'), ['order_index'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_user_id'), ['user_id'], unique=False)

    op.create_table('read_rewards',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chapter_id', sa.BigInteger(), nullable=False),
    sa.Column('coins_earned', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chapter_id', name='uq_user_chapter_reward')
    )
    with op.batch_alter_table('read_rewards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_read_rewards_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_read_rewards_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_read_rewards_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('read_rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_read_rewards_user_id'))
        batch_op.drop_index(batch_op.f('ix_read_rewards_id'))
        batch_op.drop_index(batch_op.f('ix_read_rewards_chapter_id'))

    op.drop_table('read_rewards')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comments_id'))
        batch_op.drop_index(batch_op.f('ix_comments_chapter_id'))

    op.drop_table('comments')
    with op.batch_alter_table('chapter_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_images_order_index'))
        batch_op.drop_index(batch_op.f('ix_chapter_images_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_images_chapter_id'))

    op.drop_table('chapter_images')
    op.drop_table('webtoon_genres')
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_webtoon_id'))
        batch_op.drop_index(batch_op.f('ix_chapters_status'))
        batch_op.drop_index(batch_op.f('ix_chapters_id'))
        batch_op.drop_index(batch_op.f('ix_chapters_chapter_number'))

    op.drop_table('chapters')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmarks_webtoon_id'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_status'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_id'))

    op.drop_table('bookmarks')
    with op.batch_alter_table('wheel_spins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wheel_spins_wheel_id'))
        batch_op.drop_index(batch_op.f('ix_wheel_spins_user_id'))
        batch_op.drop_index(batch_op.f('ix_wheel_spins_id'))
        batch_op.drop_index(batch_op.f('ix_wheel_spins_created_at'))

    op.drop_table('wheel_spins')
    with op.batch_alter_table('webtoons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webtoons_type'))
        batch_op.drop_index(batch_op.f('ix_webtoons_title'))
        batch_op.drop_index(batch_op.f('ix_webtoons_slug'))
        batch_op.drop_index(batch_op.f('ix_webtoons_id'))

    op.drop_table('webtoons')
    with op.batch_alter_table('staff_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_sessions_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_sessions_refresh_token_hash'))

    op.drop_table('staff_sessions')
    with op.batch_alter_table('creator_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_creator_requests_status'))
        batch_op.drop_index(batch_op.f('ix_creator_requests_id'))

    op.drop_table('creator_requests')
    with op.batch_alter_table('coin_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_coin_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_coin_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_coin_transactions_created_at'))

    op.drop_table('coin_transactions')
    with op.batch_alter_table('clan_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clan_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_clan_messages_id'))
        batch_op.drop_index(batch_op.f('ix_clan_messages_clan_id'))

    op.drop_table('clan_messages')
    with op.batch_alter_table('clan_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clan_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_clan_members_id'))
        batch_op.drop_index(batch_op.f('ix_clan_members_clan_id'))

    op.drop_table('clan_members')
    with op.batch_alter_table('wheel_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wheel_items_wheel_id'))
        batch_op.drop_index(batch_op.f('ix_wheel_items_id'))

    op.drop_table('wheel_items')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_refresh_token_hash'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_inventory_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_item_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_id'))

    op.drop_table('user_inventory')
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_users_username'))
        batch_op.drop_index(batch_op.f('ix_staff_users_id'))
        batch_op.drop_index(batch_op.f('ix_staff_users_email'))

    op.drop_table('staff_users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_user_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_id'))
        batch_op.drop_index(batch_op.f('ix_friendships_friend_id'))

    op.drop_table('friendships')
    with op.batch_alter_table('clans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clans_tag'))
        batch_op.drop_index(batch_op.f('ix_clans_name'))
        batch_op.drop_index(batch_op.f('ix_clans_id'))

    op.drop_table('clans')
    with op.batch_alter_table('wheels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wheels_slug'))
        batch_op.drop_index(batch_op.f('ix_wheels_is_active'))
        batch_op.drop_index(batch_op.f('ix_wheels_id'))

    op.drop_table('wheels')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('shop_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_items_item_type'))
        batch_op.drop_index(batch_op.f('ix_shop_items_id'))

    op.drop_table('shop_items')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_id'))
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres_slug'))
        batch_op.drop_index(batch_op.f('ix_genres_id'))

    op.drop_table('genres')
    with op.batch_alter_table('clan_level_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clan_level_configs_level'))

    op.drop_table('clan_level_configs')
    # ### end Alembic commands ###
