"""idempotent chapter image uploads

Revision ID: fd7b101e6be6
Revises: f1ddbfdecbb4
Create Date: 2026-10-03 14:48:48.626054
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd7b101e6be6'
down_revision: Union[str, None] = 'f1ddbfdecbb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_upload_batches',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'idempotency_key', name='uq_chapter_upload_batch')
    )
    with op.batch_alter_table('chapter_upload_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_upload_batches_chapter_id'), ['chapter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_upload_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_upload_batches_chapter_id'))

    op.drop_table('chapter_upload_batches')
    # ### end Alembic commands ###
